# Generated by Django 3.0.6 on 2020-06-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Moviereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('sentinaive', models.CharField(max_length=100)),
                ('sentivader', models.CharField(max_length=100)),
                ('movieid', models.IntegerField()),
            ],
            options={
                'db_table': 'moviereview',
            },
        ),
    ]
